### ISSUE TITLE
When opening wiki, open article for corresponding challenge

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki-generator#12]
Agile user story:
- As a user, when I click the wiki button, the wiki should slide out with the article that corresponds to my current challenge, if one exists.

Relates https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8108
Closes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8108
Being fixed at https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8373

**Comment by vcooley** [comment]
I'm working on this right now. I'm new to contributing, but I've been reading through the wiki pages and main site code and have some ideas on how to implement this. 

A couple questions:

What is the policy when new challenges are added? Is it guaranteed that a new wiki article is added? 

As far as I can tell there is a solution page to each challenge and algorithm. Is this true in the site's current state (with a couple exceptions such as what used to be called "Basejumps")?

**Comment by Rafase282** [comment]
@vcooley when a new challenge is created then we have to create an article for it. Which is why we point to it if it exist. 

We do try to make articles for all challenges but the more advance ones need support.

**Comment by Rafase282** [comment]
I have merged the fixes, now you can work on this. When a new challenge is made, the article needs to be created manually. @vcooley let me know if you will still work on this feature.

**Comment by vcooley** [comment]
@Rafase282 

Still want to work on it. I've got a couple issues though, mainly we want to direct the user to the appropriate page in their language, if available, and redirect to the english page if unavailable. See [#8373](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8373). I'm not familiar with the wiki structure yet, so is it a possibility to add redirection on the wiki's side on a 404?

**Comment by Rafase282** [comment]
We have problems with the internal linking on the generator site, but it does create directories and files for other languages. Come over to the [chat room](https://gitter.im/FreeCodeCamp/Wik).

**Comment by Rafase282** [comment]
@vcooley I just want to update you in case you haven't been following the pull request. Right now the generator is ready, the redesign will be merged shortly and everything else was solve aside from this and making the pages crawl-able.

**Comment by Rafase282** [comment]
I though it should be handled on the FCC side but if there is a way to get the URL it is called from then I can probably have it display the right article by matching the names.

**Comment by vcooley** [comment]
See [#8591](https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8591). I have PR [#8373](https://github.com/FreeCodeCamp/FreeCodeCamp/pull/8373) that links to the english version of the challenges. 

So while the wiki is hosted on github pages, it doesn't seem possible to direct a user to the correct page and guarantee that the user won't get a 404. It might be possible to build a 404 page that handles the redirection from the wiki's side of things.

**Comment by Rafase282** [comment]
I took a quick look, the url should be `https://www.freecodecamp.com/wiki/` the one you have there points to the github page while if you switch to the one I pointed it will direct to the wiki on the site.

**Comment by vcooley** [comment]
Oh, so the wiki is now hosted on the main site? That's great and should simplify things a lot. The biggest issue in redirection was that you couldn't read the iframe's content due to the being hosted on a different origin.

**Comment by vcooley** [comment]
I'll fix that PR real quick.

**Comment by Rafase282** [comment]
No, it is not hosted there, it is still hosted on github but the "official" link is `https://www.freecodecamp.com/wiki/en/Accessing-Database-Front-End/` it pulls an iframe witth the pages. The links are internally changed to point to the fcc domain and not the github page so in a way you can treat it as if the pages were on the fcc server.

**Comment by vcooley** [comment]
Ah I see. So we're still going to have the same issue with knowing if a solution page exists or not. Unfortunately, there's no way to read the contents of the iframe from the main window when the source is from a different origin.

**Comment by Rafase282** [comment]
But can't you just use the url? Care to chat [here](https://gitter.im/FreeCodeCamp/Wiki) ?

**Comment by Rafase282** [comment]
It has been confirmed, we just have tow orry about English articles until there is an official release in another language. @vcooley

**Comment by Rafase282** [comment]
@vcooley it seems to work for me.

> Works for all challenges not just algorithms.

![Imgur](http://i.imgur.com/sff2rDK.png)

![Imgur](http://i.imgur.com/WNCqlVk.png)
