### ISSUE TITLE
Design alternative to wiki dropdown menu

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki-generator#13]
With the increasing number of articles in our wiki, this dropdown menu is impractical. It would be much better if it were somehow searchable.

Relates to and closes https://github.com/FreeCodeCamp/FreeCodeCamp/issues/8107

**Comment by DanAdrenaline** [comment]
I have been having a look at the Wiki site and it looks like the search box and combo box are two different items, though I cant work out how the app transitions the sidebar when on smaller screens?

I have had  look around a few other sites for similar cases: an example I found was the [Telerik site](http://demos.telerik.com/kendo-ui/combobox/index) seen on the left.

The [React-toolbox auto-complete](http://react-toolbox.com/#/components/autocomplete) looks to be a good option, though I don't see a on select event to fire off the navigation. P.s. I am new to react which this seems to be written in.

Another example written in C# can be found here: [http://www.codeproject.com/Tips/755707/ComboBox-with-Suggestions-Based-on-Loose-Character](http://www.codeproject.com/Tips/755707/ComboBox-with-Suggestions-Based-on-Loose-Character)

**Comment by Rafase282** [comment]
We have been talking about removing the dropdown to have a full far for that wont be intrusive that will list articles as you type.

I'm currently engaging on fixing the generator so I haven't laid down much details yet.

**Comment by DanAdrenaline** [comment]
See some examples below. Or a simpler one that looks more like the codepen example, with a search icon next to the Free Code Camp Logo that expands to the embedded search header.

This could be totally independent of the right hand bar on larger screens, to create a more unified experience.

Apologies they are so big, not idea how to scale on GitHub
![wiki mobile image with search header](https://cloud.githubusercontent.com/assets/17498678/15017423/6e6bb0f0-120d-11e6-85b9-c1241e4e630c.png)
![wiki mobile image with embedded search header](https://cloud.githubusercontent.com/assets/17498678/15017424/6e6bdc9c-120d-11e6-889c-136d20451c53.png)

**Comment by Rafase282** [comment]
This is another version from my pen, it is jus tnot visible until your login into my app.

![MangaDB](http://i.imgur.com/IJdbCZr.png)

**Comment by Rafase282** [comment]
I have merged the fixes for the generator, now you can work on this and test it.
