### ISSUE TITLE
[Feature] Support emoji

### ISSUE THREAD

**Issue by abhisekp** [FreeCodeCamp/wiki-generator#22]
Support for emoji required as a lot of wiki articles use emoji and Github markdown supports emojis. 

arising from https://github.com/FreeCodeCamp/wiki/issues/874

**Comment by Rafase282** [comment]
Do you have any ideas as to how to implement this?

**Comment by Rafase282** [comment]
I found this [this](https://github.com/pamo/pamo.github.io/blob/development/loaders/markdown-loader/index.js) 

It uses [markdown-it-emoji](https://www.npmjs.com/package/markdown-it-emoji)

**Comment by pamo** [comment]
I fully support this 😝.
Let me know if you need help 😁

**Comment by Rafase282** [comment]
Yes, currently no one is working on this yet.

**Comment by Rafase282** [comment]
@pamo currently there is no one actively working on this. It would be awesome if you could help with it, after all, you already have the experience.

You can directly chat with us on gitter at [FreeCodeCamp/Wiki](https://gitter.im/FreeCodeCamp/Wiki)
