### ISSUE TITLE
The generator dos not preview with the full CSS

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki-generator#25]
When the preview is ruing this is what we see

![Imgur](http://i.imgur.com/9aUx5Ve.png)

**Comment by DanAdrenaline** [comment]
```
.wiki-container{max-width:100%;padding:40px 15px;box-sizing:border-box;display:inline-block;width:100%;height:100%;margin:0 auto;position:relative;overflow-x:hidden;overflow-y:auto;-webkit-overflow-scrolling:touch}
```

I think this is the fix in the Main.CSS I cant work out how to branch/fork to make this change

**Comment by Rafase282** [comment]
@DanAdrenaline come over to the chat room please.

**Comment by Rafase282** [comment]
Turns out that the navbar is part of the FCC site not the generator and side bar displays on `/en` which is supposed to be the root so all is well as it should on that end.
