### ISSUE TITLE
Mobile Responsiveness

### ISSUE THREAD

**Issue by ghost** [FreeCodeCamp/wiki-generator#27]
#### Issue Description

Images aren't responsive on wiki.
#### Screenshot

![](https://i.gyazo.com/54ff715954f31517e804ae5eb541b63d.png)

**Comment by DanAdrenaline** [comment]
Good point about the Images on mobile.

The search bar has already been highlighted by issue #13

**Comment by Rafase282** [comment]
I already took care of this on the PR, pushed lives this particular change.
