### ISSUE TITLE
Hard coded language when linking to wiki

### ISSUE THREAD

**Issue by raisedadead** [FreeCodeCamp/wiki-generator#29]
Need to implement a mechanism for automatic re-directs as mentioned in 
FreeCodeCamp/FreeCodeCamp#8591

**Comment by BerkeleyTrue** [comment]
Unfortunately, static pages don't work like that. You can't have automatic pages. If it's not there you get a 404 page.

**Comment by raisedadead** [comment]
Oh that's correct, I almost forgot about this!
wiki-generator builds the static pages and all this is served from GitHub Pages.

Thanks @BerkeleyTrue !
