### ISSUE TITLE
Wiki articles are too wide and get truncated

### ISSUE THREAD

**Issue by QuincyLarson** [FreeCodeCamp/wiki-generator#34]
![](https://www.evernote.com/l/Ar-SKvneBldH8IiSbj19i__Toq8y-wYWxYsB/image.png)

**Comment by ghost** [comment]
This is also an issue on small screens using **freecodecamp.com/wiki** directly.

![.markdown selector](https://cloud.githubusercontent.com/assets/11198912/15420505/f0a821ee-1e64-11e6-964a-00fcf165075a.png)

I believe this can be changed to:

``` css
.markdown {
  margin-right: 70px;
}
```

Correct me if I'm wrong...

**Comment by Rafase282** [comment]
What browser is that? I don't get that issue on chromium.

![Imgur](http://i.imgur.com/nLBMx8H.png)
