### ISSUE TITLE
Alternative to typography?

### ISSUE THREAD

**Issue by Rafase282** [FreeCodeCamp/wiki-generator#4]
Any chance that `typography` can be switched to something else? Me and @hallaathrad tried to set it up locally on my raspberry pi witch raspbian and that particular part of the script is what prevented it from working.

**Comment by justincorrigible** [comment]
we would ideally be able to do without it, considering we design the CSS ourselves anyway.

**Comment by Rafase282** [comment]
That would implies the scripts have to be changed to not use it. Was this taken from a template or built from the groundup?

**Comment by justincorrigible** [comment]
changing this too ;) hang tight!

**Comment by Rafase282** [comment]
Good!
