### ISSUE TITLE
Some emojis don't show

### ISSUE THREAD

**Issue by ghost** [FreeCodeCamp/wiki-generator#53]
:memo: (`:memo:`) doesn't seem to be rendering here: https://www.freecodecamp.com/wiki/en/algorithm-reverse-a-string/.

This is an issue with emojione and not our wiki.

**Comment by Rafase282** [comment]
Doesn't seem to be a good option based on the last update and status. See: https://github.com/Ranks/emojify.js#emojifyjs

**Comment by ghost** [comment]
@Rafase282 Do you suggest we set a specific test case for this problem? I can't find another alternative that does what we want.

**Comment by Rafase282** [comment]
I propose we use an alternative that they have

http://emojione.com/#gallery

I'm looking for alternative, if there were many emojis that we  were missing then we should switch, but I personally prefer to stick with the one who stills gets updated and gets new emojis.

:memo: works as `memo`
